spring:
  profiles:
    active: local
server:
  port: 8083
---
spring:
  profiles: local
# memory datasource configuration
  memorydb:
    datasource:
      url: jdbc:h2:mem:testdb
      username: avinash
      password: avinash
      driver-class-name: org.h2.Driver
    jpa:
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
    h2:
      console:
        enabled: true
  # mysql datasource configuration
  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/employee_db?autoReconnect=true&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: create
        hbm2ddl:
          auto: update
    mysql:
      console:
        enabled: true

